services:
  postgres:
    image: postgres:16-alpine
    container_name: fittrack-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: fittrack_pro
      POSTGRES_USER: fittrack_dev
      POSTGRES_PASSWORD: fittrack_dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
